version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    image: ai-hedge-fund-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ../app/frontend:/app/frontend
      - /app/frontend/node_modules

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: ai-hedge-fund-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    environment:
      - ENV_FILE=../.env
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama_data: {}